### PR TITLE
Parallel autodiff v2 RFC

### PR DESCRIPTION
**Pull request by wds15**
This RFC introduces the basic design elements needed to evaluate functions with parallelism during reverse mode autodiff of stan-math.

The RFC aims to introduce

- parallel reduce
- parallel map

to stan math on the basis of the Intel TBB library. To achieve this, the RFC intends to

- refactor the AD tape to allow using multiple processes
- refactor nested AD to be compatible with parallelism

A lot of discussions on the topic have taken place in 2019. Here are some links to previous discussions:

- Initial PR of first RFC, [see here](https://github.com/stan-dev/design-docs/pull/5)
- Parallel autodiff v2 [discourse  discussion](https://discourse.mc-stan.org/t/parallel-autodiff-v2/12221)
- Performance evaluation of a prototype on [discourse](https://discourse.mc-stan.org/t/benefits-of-parallelization-with-a-threadpool-of-the-intel-tbb/9704)

In contrast to the first RFC, this version now tries to spell out more clearly the requirements needed. Moreover, the Intel TBB is taken for granted as it is now in stan-math.

A [rendered version can be found here](https://github.com/stan-dev/design-docs/blob/396dab8ce4db2732f919c628d1b5575798793408/designs/0003-parallel_autodiff.md).

### CODE REVIEW

**Comment by wds15** [comment]
@SteveBronder is your comment related to the current version? The comment is dated May 29th...

**Comment by SteveBronder** [comment]
Nope! dunno why it was there

**Comment by wds15** [comment]
While this PR would still be of interest to progress along, there is now an alternative approach available which enables parallelism without refactoring the AD tape (at the cost of some flexibility):

See here:

https://discourse.mc-stan.org/t/parallel-autodiff-v3/12474/22

So we can probably put the review of this at rest for the moment being.

**Comment by wds15** [comment]
Let's close this one.

**Pull request closed without merging**
