### PR TITLE
JSON Sampling output

### PR DESCRIPTION
**Pull request by rok-cesnovar**
I am requesting comments on my proposal to add JSON output to Cmdstan as previously discuss [here](https://github.com/stan-dev/cmdstan/issues/789).

See the [rendered version](https://github.com/stan-dev/design-docs/blob/ebd39a0a43d1abc5ab1cda700f2f290e31efb27c/designs/0007-json_writer.md).

### CODE REVIEW

**Comment by bob-carpenter** [comment]
`inverse_mass_matrix` should be `euclidean_metric`.

There's a dangling clause "rjson but only supports the standard JSON."

What does "NA" mean in JSON?  We want not-a-number, not undefined.  So we don't want R's version of "NA".

Can we make a PR ourselves to jsonlite perhaps to make it easier?  We should see if they want the change first, but that would indeed be the easiest.  

I still don't understand what supporting two versions would entail.  I'm concerned about us defining what amounts to a double standard (pun intended).

With `special_values_encoding=js or special_values_encoding=string or special_values_encoding=na` it looks like three different encodings.  I don't think we should use `na` as it's just too confusing with R.  Shouldn't "js" be "json", because we're referencing the "javascript object notation"?

What's the JSON/CSV line in the performance report?

Are you using a JSON lib to do the output?  Any idea why it's faster?  I can imagine buffering or faster double-precision to string routines.

Does JSON handle denormalized numbers?  We've had problems with this in I/O before.  We should probably take a stand on whether we support their use in Stan.

"I do not see any real drawbacks, except for additional code to maintain in the codebase."  Although it's not a drawback per se, this also complicates the doc and requires more doc to be maintained.  It's not free to add new functionality, even if it's optional, as it complicates the interface and makes it harder to use as the doc gets longer.

I believe protobuf comes with a protobuf to JSON converter.  The beauty of protobuf is that it should be a lot faster with binary I/O.

What is the restart proposal?  Imagine we're in the middle of a run and writing JSON when our cluster times out.  What happens to the output?  Restarting is also going to require more I/O wrangling, so won't be free (I'm all for it, though, as it's a feature we could use).  Restart is hard if you want to save the seed so as to get the same result as if you hand't restarted.  The state of our RNGs is bigger than their seed.

We defiitely don't want to produce rdump format.  The problem is that dump in R is uncontrolled---it uses arbitrary R in the output (for instance, producing `1:5` instead of `c(1, 2, 3, 4, 5)`.  


Would we change all the output commands to not only specify CSV vs. JSON, but also to choose among different encodings in JSON?   I'm concerned about having

**Comment by riddell-stan** [comment]
I've read this (quickly).

Thank you for your work on this @rok-cesnovar .

My sense is that this is an incremental improvement on `stream_writer.hpp`. It's a regression, however, in that stream_writer.hpp already handles nan and inf in a predictable (insofar as CSV is a standard).

@syclik  said something about re-imagining the writer class at some point. What happened to that discussion?

Maybe we could do that and simultaneously settle on a protocol buffer schema that satisfies everyone? One plus for protobuf is that we can encode inf and nan values. With some work I suspect we could come up with a solution for NA values (a mask array?). If we had a group of 3 people invested in the problem I bet we could come to a solution that's much better than using JSON.

I'm invested in getting something better than stream_writer.hpp into Stan. (Last month I wrote a [protobuf version of stream_writer.hpp for httpstan](https://github.com/stan-dev/httpstan/blob/eeee0419dbea7bc69c86e12c27b86f5167caf111/httpstan/queue_writer.hpp); but I'm not happy with it). I'm happy to help work on this if others are interested.

**Comment by bob-carpenter** [comment]
> On Jan 6, 2020, at 12:26 PM, riddell-stan <notifications@github.com> wrote:
> 
> I've read this (quickly).
> 
> Thank you for your work on this @rok-cesnovar .
> 
> My sense is that this is an incremental improvement on stream_writer.hpp. It's a regression, however, in that stream_writer.hpp already handles nan and inf in a predictable (insofar as CSV is a standard).

The fundamental problem isn't implementation, but that there's no standard for not-a-number and infinite values in JSON.  The standard packages in Python and R have gone different ways in their non-standard support.


> @syclik said something about re-imagining the writer class at some point. What happened to that discussion?
> 
> Maybe we could do that and simultaneously settle on a protocol buffer schema that satisfies everyone? One plus for protobuf is that we can encode inf and nan values. With some work I suspect we could come up with a solution for NA values (a mask array?).

By "NA", I take it you mean the R notion of undefined values?  If so, what's the use case given that Stan programs don't recognize undefined values?  I prefer the long-form data solution to the NA solution anyway as it doesn't require non-standard floating point values.  


> If we had a group of 3 people invested in the problem I bet we could come to a solution that's much better than using JSON.

We could certainly come up with something more performant, but I don't know how we could do much better with a human-readable format.

The big advantages aren't the format, but that it'll be easier to support other features like restarting.  The format would be an advantage if there was a standard that dealt with NaN and infinity.

Rok suggests that wouldn't be easy or possible with protobuf output.  I'm not an expert, so I'll leave it to you two to hash out.

> I'm invested in getting something better than stream_writer.hpp into Stan. (Last month I wrote a protobuf version of stream_writer.hpp for httpstan; but I'm not happy with it). I'm happy to help work on this if others are interested.

I would very much like a binary output version.  We got hung up last time
around the every-draw-needs-meta-information discussion, if I'm remembering correctly.  Also, protobuf explicitly states it shouldn't be used for large output files:

  Protocol Buffers are not designed to handle large messages. As a general rule of 
  thumb, if you are dealing in messages larger than a megabyte each, it may be 
  time to consider an alternate strategy.

  from: https://developers.google.com/protocol-buffers/docs/techniques#large-data

But maybe that's a conservative warning.  It also looks like reading is brittle for arbitrary-sized streams (much like our current brittle output!):

  The Protocol Buffer wire format is not self-delimiting, so protocol buffer 
  parsers cannot determine where a message ends on their own. The easiest way to 
  solve this problem is to write the size of each message before you write the 
  message itself. When you read the messages back in, you read the size, then read 
  the bytes into a separate buffer, then parse from that buffer.

  from: https://developers.google.com/protocol-buffers/docs/techniques#streaming

**Comment by rok-cesnovar** [comment]
> `inverse_mass_matrix` should be `euclidean_metric`.

Thanks! I didnt spend much time on arguments as I am sure all of you have a better idea what should the names be. Will update the doc.

> There's a dangling clause "rjson but only supports the standard JSON."

I mean that rjson only supports what the JSON standard defines, which means no special values. Will fix in the doc.

> What does "NA" mean in JSON? We want not-a-number, not undefined. So we don't want R's version of "NA".

NA is undefined yes. This is just an idea how we could output standard-compliant JSON if there was a need (replace Inf, -Inf and NaN with NA or null that are allowed by the standard). I dont think this has much use. Just throwing it out there.

> Can we make a PR ourselves to jsonlite perhaps to make it easier? We should see if they want the change first, but that would indeed be the easiest.

I made an issue here: https://github.com/jeroen/jsonlite/issues/302 If I get positive feedback I will do just that.

> Shouldn't "js" be "json", because we're referencing the "javascript object notation"?

By specifying "js" the user specifies that special values are encoded the same way they are in Javascript (what python json package consumes). By string the user would specify that special values are encoded as strings "NaN", which is what jsonlite consumes. I am going to remove the NA suggestion, its a bad idea anyways.

> What's the JSON/CSV line in the performance report?

Just the ratio of execution times to see how much difference there is relatively to CSV exec. times.

> Are you using a JSON lib to do the output? Any idea why it's faster? I can imagine buffering or faster double-precision to string routines.

Yes, I used rapidjson for output. I would bet on faster double-precision to string. I am also using more precision in JSON (6 vs 5 used in csv), so we can rule out precision issues. But I have not done extensive performance tests. Also plan on benchmarking memory use.

> Does JSON handle denormalized numbers? We've had problems with this in I/O before. We should probably take a stand on whether we support their use in Stan.

It does on input, Dont know for output. Will check. Thanks!

Will split my answers in multiple posts.

**Comment by bob-carpenter** [comment]
> NA is undefined yes. This is just an idea how we could output standard-compliant JSON if there was a need (replace Inf, -Inf and NaN with NA or null that are allowed by the standard). I dont think this has much use. Just throwing it out there.

We need to encode +inf, -inf, and NaN separately.  I think transcoding one or more of these as NA would be too confusing.  

> 
> Can we make a PR ourselves to jsonlite perhaps to make it easier? We should see if they want the change first, but that would indeed be the easiest.
> 
> I made an issue here: jeroen/jsonlite#302 If I get positive feedback I will do just that.

Awesome!

> 
> Shouldn't "js" be "json", because we're referencing the "javascript object notation"?
> 
> By specifying "js" the user specifies that special values are encoded the same way they are in Javascript (what python json package consumes).

My point was that "JSON" is an acronym for "javascript object notation", so isn't going with javascript the same as going with default JSON?  I understand that specifying "json" would be confusing, but then so is "js" if you know the relation between JS and JSON.  Perhaps another option?

> By string the user would specify that special values are encoded as strings "NaN", which is what jsonlite consumes.

NaN looks like a string to me.  Maybe "quoted" instead of "string"?


> I am going to remove the NA suggestion, its a bad idea anyways.

Thanks!


> What's the JSON/CSV line in the performance report?
> 
> Just the ratio of execution times to see how much difference there is relatively to CSV exec. times.

D'oh!

**Comment by mike-lawrence** [comment]
When you say "The only realistic alternative I see is skipping the step of introducing a JSON output and going with binary output. But that will not enable some requested features like restarting.", I'm confused as to what barrier manifests in the binary formats that prevent restarting.

**Comment by betanalpha** [comment]
The terminology used in the HMC code is “inv_metric” and I would recommend that here.

Inverse is important because it’s not a metric on the parameter space but rather the 
momentum space.  Euclidean is technically redundant here as all metrics we’d use in
Stan for a long time are actually Euclidean (yes even including what everyone calls
“Riemannian HMC”).

**Comment by rok-cesnovar** [comment]
> Although it's not a drawback per se, this also complicates the doc and requires more doc to be maintained.

Agreed, will add to the doc.

> What is the restart proposal? Imagine we're in the middle of a run and writing JSON when our cluster times out. What happens to the output?

I meant the idea of doing restarts yes. There is no proposal in the sense of hashed out details. If the execution stops unexpectedly and Cmdstan doesnt exit cleanly, JSON will not be valid (would need a "] }" at the end). Will add that point to the doc.

> Would we change all the output commands to not only specify CSV vs. JSON, but also to choose among different encodings in JSON?

The different encodings would be handled by rapidjson. We would specify it when instantiating the rapidjson writer. We then just use its functions like writer.writeDouble(val). The rest is done by rapidjson.

> It's a regression, however, in that stream_writer.hpp already handles nan and inf in a predictable (insofar as CSV is a standard).

I am not sure I agree on the point that it would be a regression. I feel there is value in another human-readable output that would work on other features. It might also be faster, at least it seems so. And yes, the speed diff will be negligible when the log-prob evaluation takes a substantial amount of time.

> Maybe we could do that and simultaneously settle on a protocol buffer schema that satisfies everyone?

Yes, please! I am happy to work on the binary format also.

**Comment by bob-carpenter** [comment]
See my previous comment with a link to protobuf's doc about sizing and big data.

The issue is that protobuf's not a self-terminating format, so you need to specify how big something is before you start generating.  If it stops partway through, you get ill-formed protobufs.

I already have a question out to Rok asking how JSON can support restarting, as I assume we'd also get unterminated and ill-formed JSON if we just pull the plug on output partway through.

**Comment by mike-lawrence** [comment]
> The issue is that protobuf's not a self-terminating format, so you need to specify how big something is before you start generating.  If it stops partway through, you get ill-formed protobufs.

Ah, then I suggest not painting all binary formats with that brush. HDF5 is self-terminating for example (hence it's ability to write in single-writer/multiple-readers mode).

**Comment by rok-cesnovar** [comment]
> Rok suggests that wouldn't be easy or possible with protobuf output. I'm not an expert, so I'll leave it to you two to hash out.

> When you say "The only realistic alternative I see is skipping the step of introducing a JSON output and going with binary output. But that will not enable some requested features like restarting.", I'm confused as to what barrier manifests in the binary formats that prevent restarting.

Yeah, the same could be done with protobuf, once we add protobuf to input. I meant more in the sense that its something we could use right now. Will improve the text, sorry.

> I already have a question out to Rok asking how JSON can support restarting, as I assume we'd also get unterminated and ill-formed JSON if we just pull the plug on output partway through.

You are correct. I noted that in the comment above. One option for restarts would be to offer a restart_file.json that would always hold the last state of whatever we need for restart. That would be very unefficient tho. This is something a PR for restarts would need to hash out.

**Comment by rok-cesnovar** [comment]
I updated the docs based on the first round of comments. For now I went with "inv_euclidean_metric", but these names are probably something that needs to be hashed out separately. I definitely dont have enough background on most of them to have an opinion.

Hopefully I also answered all the questions so far. If not, do say so.

To re-iterate I am not against working on binary output/input. I am very much for! I don't see this as a JSON or binary design doc. My plan was to first work on this and then move to binary if someone else doesn't pick that up in the meantime.

**Comment by bob-carpenter** [comment]
> On Jan 6, 2020, at 1:28 PM, Mike Lawrence <notifications@github.com> wrote:
> 
> The issue is that protobuf's not a self-terminating format, so you need to specify how big something is before you start generating. If it stops partway through, you get ill-formed protobufs.
> 
> Ah, then I suggest not painting all binary formats with that brush. HDF5 is self-terminating for example (hence it's ability to write in single-writer/multiple-readers mode).

That wasn't my intention---I thought we were specifically discussing protobuf.

I don't know anything about HDF5, but then I'm hardly a data serialization expert.

Multiple I/O formats are relatively orthogonal.  We just need people to design them and build them.

**Comment by riddell-stan** [comment]
These problems are both solved. With regards to sizing, we split up the 
output into distinct messages (e.g., one message for each draw). 
Individual messages are relatively small, far below the limit. With 
regards to the delimiting, there's a standard practice for this. You 
prefix each message with its length in bytes. There's even a C++ tool 
for this which ships with protobuf: 
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/delimited_message_util.cc

(re: human readable: JSON is better, you're right.)

**Comment by bob-carpenter** [comment]
> On Jan 6, 2020, at 3:35 PM, riddell-stan <notifications@github.com> wrote:
> 
> These problems are both solved. With regards to sizing, we split up the 
> output into distinct messages (e.g., one message for each draw). 


> Individual messages are relatively small, far below the limit. With 
> regards to the delimiting, there's a standard practice for this. You 
> prefix each message with its length in bytes. There's even a C++ tool 
> for this which ships with protobuf: 
> https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/delimited_message_util.cc

How are the messages broken into files?  What delimits when there are no more messages?  For restarting, will the data be readable if someone pulls the 
plug during sampling?


> (re: human readable: JSON is better, you're right.)

I don't think it's better---just satisfying a different goal that some people have.

**Comment by riddell-stan** [comment]
> How are the messages broken into files?  What delimits when there are no more messages?  For restarting, will the data be readable if someone pulls the
plug during sampling?

You can put as many of these length-delimited messages into a file as you would like. The size restriction is just on a single *message*.

> How are the messages broken into files?  What delimits when there are no more messages?  For restarting, will the data be readable if someone pulls the
plug during sampling?

If a file contains a series of length-delimited messages, you detect when the messages are done by reaching the end of the file. (It would be a bit like a file containing a newline-delimited sequence of JSON objects, like a jsonlines file.) Restarting wouldn't be difficult. If someone pulls the plug you would observe fewer complete messages than you anticipated. Each message would still be readable. Again, this is essentially the same as if we used jsonlines (newline-delimited JSON).

The main argument for protobuf vs. jsonlines is that the encoding of doubles is so much more efficient. And Stan uses tons of doubles.

**Comment by rok-cesnovar** [comment]
So for now we have 2 open questions: 

- do we skip JSON output and just move to working on binary input/ouput? My intention here was to add JSON as a complement not as an alternative to adding binary.

- If we dont skip working on JSON output, how many types of different encodings of Inf and NaN should we support. If the developers of the R package `jsonlite` will be willing to accept our pull request, we could go with a single encoding that would work with both Python and R.

**Comment by riddell-stan** [comment]
In favor of binary input/output:
1. We're almost there. This spec can be re-cast as a protobuf spec. And we have a working implementation of a (different) protobuf serialization strategy in httpstan, so we know it can work.
2. It's potentially a big improvement in speed. Parsing binary doubles is virtually certain to be faster than parsing JSON string versions of doubles.

If we do stick with JSON let's consider getting rid of the stream_writer.hpp version so we only have to maintain one thing.

**Comment by rok-cesnovar** [comment]
> 1. This spec can be re-cast as a protobuf spec.

Yes, but the binary doc needs to also thoroughly address the question of why we should be going with protobuf as opposed to any of the other numerous binary formats. And it also needs to specify how we are going to tackle binary input, creating .proto files with stanc3 etc. I do think that any design doc addressing binary should tackle both input and output.

> 2\. Parsing binary doubles is virtually certain to be faster

There is no question or doubt that binary is faster.

**Comment by riddell-stan** [comment]
> Yes, but the binary doc needs to also thoroughly address the question of why we should be going with protobuf as opposed to any of the other numerous binary formats.

There's protobuf, avro, cbor, msgpack and maybe a few others. protobuf is the most mature, has good adoption, has the best tooling.

>And it also needs to specify how we are going to tackle binary input, creating .proto files with stanc3 etc.

I think we only need binary output, I think. We would have fixed proto files. (We're only talking about an alternative to stream_writer.hpp and the equivalent logger, right?)

**Comment by bob-carpenter** [comment]
Conditioned on adding JSON support, then we need something that'll work with R and Python (and ideally Julia).  Patching jsonlite would be ideal if we could make one format that works both places.

I also see JSON as slightly complementary to protobuf.  I believe if we get protobuf, they have some kind of automatic conversion to JSON, but I have no idea whether the JSON would be useful.

**Comment by bob-carpenter** [comment]
> 	• It's potentially a big improvement in speed. Parsing binary doubles is virtually certain to be faster than parsing JSON string versions of doubles.

Raw reading of double in C++ vs. converting from strings using their built-ins is on the order of 100 times faster.

**Comment by bob-carpenter** [comment]
> And it also needs to specify how we are going to tackle binary input, creating .proto files with stanc3 etc.
> 
> I think we only need binary output, I think.

Surely we must need binary input to read what we write.  We'll need that
for any posterior inference we do.  

We'd also like to be able to read all the "meta" data like
adaptation state so that we could restart.

**Comment by rok-cesnovar** [comment]
`jsonlite` developers have declined my feature request on the basis of [1, NaN, InF] not being valid JSON ([1, "NaN, "Inf"] is valid, though I find that very ugly/confusing). So I am going to close this doc, as I have come around on this and feel that having two separate encoding is going to be confusing to the users and was hoping we could go with one.

If/When we get binary I/O we would have the option of providing something like `scripts/toJSON.R` and `scripts/toJSON.py` if there is still a need for JSON then.

**Comment by riddell-stan** [comment]
One thing I'd like to see in the spec: support for streaming the data. I think you could do this by using jsonlines instead of JSON. (Ignoring the inf/NaN issue for a moment.)

Also, I've created a post on the discussion board to summarize my thinking about serialization formats at the present moment: https://discourse.mc-stan.org/t/notes-on-stan-output-serialization-options-yaml-protobuf-avro-cbor/12837/2

One thing to note: this entire spec works fine if we replace JSON with YAML.

**Pull request closed without merging**
