### PR TITLE
CmdStanPy

### PR DESCRIPTION
**Pull request by mitzimorris**
Functional specification for CmdStanPy - lightweight python interface to CmdStan.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
I just figured it was a design doc, so I merged it.  I don't know how to unmerge.

**Comment by seantalts** [comment]
We can still use the PR for comments. I haven't looked at it since the emails a couple weeks ago - I can look again if anyone wants me to.

**Comment by mitzimorris** [comment]
@seantalts - I was looking for your input when I requested a review.

**Comment by bob-carpenter** [comment]
The flattening of the arguments with specified defaults is what I wanted and that's in there now.

**Pull request merged**
