### PR TITLE
Google Summer of Code 2020 with garch proposal

### PR DESCRIPTION
**Pull request by SteveBronder**
I'm planning to flesh out both the garch modeling proposal and lambert w proposal. 

@stablemarkets, I broke the larger document into smaller ones as I feared with one big doc and a bunch of PRs we would end up writing over each other all the time. 

pinging @asael697 and @paul-buerkner to have a look at the `garch.md` doc [rendered here](https://github.com/SteveBronder/design-docs/blob/gsoc-2020/gsoc_proposals/2021/garch.md). I feel like it should be fleshed out more with a timeline and challenges we expect

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Looks good to me. Challenges from brms side will be to determine which of all the other modeling options can be combined with GARCH models. For example, how to combine GARCH models on sigma with distributional regression in sigma. Other difficulties will be to implement all the post-processing such as posterior predictions etc. The existing ARMA terms already pave the way for all of this but we will have to figure out if the current structure is satisfactory for autoregressive terms to be applied to distributional parameters other than the mean. There are also other minor difficulties such as if/how GARCH models can be combined with a covariance formulation of ARMA models on the mean `arma(..., cov = TRUE)`. But these are all details we have to figure out in the process.

**Review by stablemarkets — DISMISSED** [review]

**Comment by stablemarkets** [comment]
@SteveBronder This looks great - agree regarding breaking up the proposal. Do we know who has write access to approve these pull requests? Once your changes are merged in, I'll go ahead and add the other components and submit my own PR.

**Comment by bob-carpenter** [comment]
@stablemarkets  All the devs have merge permission on all of our repos, so @SteveBronder will be able to merge this.

**Comment by stablemarkets** [comment]
Thanks @bob-carpenter. Still very new to Stan repos so appreciate the info!

**Comment by stablemarkets** [comment]
@SteveBronder I tried pushing a few commits to this PR (to add the other projects) but it seems like I don't have permissions. Getting an access denied message from Github.

**Comment by rok-cesnovar** [comment]
I think Steve will need to give you permissions to his fork as this PR is done from there.

**Comment by SteveBronder** [comment]
Yes sorry just sent you an collab email invite

**Comment by stablemarkets** [comment]
Thanks @SteveBronder ! I just updated with the Bayesian Benchmarking project description. So we just need the Lambert W Transform portion filled it. Any chance that could be ready ahead of our SGB meeting on Monday 2:30 ET? Hopefully SGB will review and we can send over to NumFOCUS shortly after.

**Comment by SteveBronder** [comment]
Yeah I think I can write it up today or tomorrow

**Comment by SteveBronder** [comment]
Okay added Lambert-W stuff. @spinkney can you take a look when you get a chance?

**Comment by spinkney** [comment]
I tried to add some stuff but I don't have access to the design docs repo

**Comment by SteveBronder** [comment]
Just sent you an invite to collab!

**Comment by spinkney** [comment]
Cool, added it in!

**Comment by SteveBronder** [comment]
Awesome ty! @stablemarkets I think all is good to go? I opened the PR so idt I can be the one to approve. @bbbales2 or @rok-cesnovar can you approve?

**Review by bbbales2 — APPROVED** [review]
Good!

**Comment by stablemarkets** [comment]
Sounds good! Once the changes are merged, I'll send a link to NumFOCUS so they can have it for the application. Will keep you posted on how it goes. If NumFOUS suggests edits I might reach out to individual project mentors. 

Thanks again to everyone - these projects sound really great and I'm hopeful we'll find students to push them forward.

**Comment by SteveBronder** [comment]
Cool, merged!!

**Pull request merged**
